apiVersion: v1
kind: Service
metadata: 
  name: {{ .Release.Name }}-org-svc
  labels:
    app: service-director
    cloud: azure
    {{- include "org.labels" . | nindent 4}}
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: {{ .Release.Name }}
spec:
  type: LoadBalancer
  selector:
    app: service-director
    cloud: azure
    layer: organisation
    {{- include "org.labels" . | nindent 4}}
  ports:
    - name: org 
      port: 5000
  sessionAffinity: ClientIP      

