apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-org-dep
  labels:
    app: service-director
    cloud: azure
    {{- include "org.labels" . | nindent 4}}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-director
      cloud: azure 
      layer: organisation
      {{- include "org.labels" . | nindent 6}}
  template:
    metadata:
      labels:
        app: service-director
        cloud: azure
        layer: organisation
        {{- include "org.labels" . | nindent 8}}
    spec:
      containers:
        - name: c1
          image: robin2310/organisation-app:latest
          env:
            - name: SITE_NAME
              value: {{ .Values.SITE_NAME }}
            - name: ORG_PORT
              value: {{ .Values.ORG_PORT | quote}}
            - name: SITE_PORT
              value: {{ .Values.SITE_PORT | quote}}
          livenessProbe:
            httpGet:
              path: /
              port: 6000
            initialDelaySeconds: 15